### ISSUE TITLE
Move to AGPL

### ISSUE THREAD

**Issue by ghost** [adfinis-sygroup/pure_func#6]
@sliverc @lucaswiman 

I want to switch to AGPL, not that it matters for the project, it's more a statement. I am currently moving all code I can to AGPL, because of recent events in the "cloud".

Please answer in that issue whether you agree or not.

**Comment by lucaswiman** [comment]
I personally dislike the AGPL and related copyleft licenses since it makes it much, much harder to use libraries for commercial use. Commercial use is something I don't have a problem with in the abstract. Indeed, almost all of my FOSS contributions have been in the context of my work as a commercial software developer. As an analogy, I think academic research should also be open and usable in industry, even if it may in some cases be misused.

While of course commercial users could decide to release all their source code (including trade secrets) in order to use a small library about testing functional purity, literally no such users will do so because of this library. If any commercial users with closed-source codebases currently use this library, they will need to replace or remove it, which just seems like a deadweight loss of pointless work.

That said, I made one extremely minor typo correction and didn't end up using this library for anything. Since the contribution was so minor, I don't think my voice should have any weight on decisions made on this library, so I authorize relicensing my contribution under the AGPL if that's what you want to do.

**Comment by ghost** [comment]
Lucas thank you very much for the detailed explanation. I really appreciate your feedback. I am torn between positions. I used to use BSD or MIT for everything. In the last couple of years I have seen very bad behavior by some big tech companies. I don't care about commercial/non-commercial, I want the FOSS projects to be healthy. I am actually not sure if AGPL helps, moving my little libraries to AGPL is more a statement for FOSS, than anything else. Many important projects have to use permissive licenses and I totally understand that. Imagine the Python license not being permissive.

I'll leave the license. Thank you for your feedback and sorry for the noise. :smile:
